---
# tasks file for ansible-role-docker-container-vault
- name: docker_container - {{ docker_container_vault_volume_dir }}
  ansible.builtin.file:
    path: "{{ docker_container_vault_volume_dir }}/{{ item }}"
    owner: "100"
    group: "1000"
    state: directory
  loop: ["data", "policies"]

- name: docker_image pull {{ docker_image_vault_name }}
  community.docker.docker_image:
    name: '{{ docker_image_vault_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_vault_pull

- name: docker_network {{ docker_container_vault_name }}
  community.docker.docker_network:
    name: "{{ docker_network_vault_name }}"
    driver: "{{ docker_network_vault_driver | default('bridge') }}"
    attachable: "{{ docker_network_vault_attachable | default(true) }}"
    enable_ipv6: "{{ docker_network_vault_enable_ipv6 | default(false) }}"
    internal: "{{ docker_network_vault_internal | default(false) }}"
    state: present


- name: docker_container {{ docker_container_vault_name }}
  community.docker.docker_container:
    name: "{{ docker_container_vault_name }}"
    comparisons: "{{ docker_container_vault_comparisons }}"
    image: "{{ docker_container_vault_image }}"
    state: "{{ docker_container_vault_state | default('started') }}"
    recreate: "{{ docker_container_vault_recreate | default(false) }}"
    restart: "{{ docker_container_vault_restart | default(false) }}"
    restart_policy: "{{ docker_container_vault_restart_policy | default('always') }}"
    capabilities: "{{ docker_container_vault_capabilities | default(omit) }}"
    command: "{{ docker_container_vault_command | default(omit) }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_vault_auto_remove | default(false) }}"
    detach: "{{ docker_container_vault_detach | default(true) }}"
    init: "{{ docker_container_vault_init | default(false) }}"
    interactive: "{{ docker_container_vault_interactive | default(false) }}"
    keep_volumes: "{{ docker_container_vault_keep_volumes | default(true) }}"
    memory: "{{ docker_container_vault_memory | default('0') }}"
    paused: "{{ docker_container_vault_paused | default(false) }}"
    privileged: "{{ docker_container_vault_privileged | default(false) }}"
    read_only: "{{ docker_container_vault_read_only | default(false) }}"
    tty: "{{ docker_container_vault_tty | default(false) }}"
    env_file: "{{ docker_container_vault_env_file | default(omit) }}"
    env: "{{ docker_container_vault_env | default(omit) }}"
    volumes: "{{ docker_container_vault_volumes | default(omit) }}"
    labels: "{{ docker_container_vault_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_vault_networks_cli_compatible | default(true) }}"
    network_mode: "{{ docker_network_vault_name }}"
    pull: "{{ docker_container_vault_pull | default(false) }}"
    networks: "{{ docker_container_vault_networks }}"
    published_ports: "{{ docker_container_vault_ports | default(omit) }}"
    # user: "{{ docker_container_vault_user | default(omit) }}"
